### ISSUE TITLE
Any news regarding WC working with Torch Concealment ?

### ISSUE THREAD

**Issue by MaceUD** [sstixrud/WeaponCore#135]
Hey, I just checked all isues and I don't see the one concerning Torch concealment anymore.
So I wonder, does it means it works with it now ?

Sincerely,
Mace

**Comment by sstixrud** [comment]
There are still reports of issues, even after WC added code to make it compatible.  This is not actively being worked on at this time.

**Comment by SeanTrig** [comment]
Concealment is a huge boon to servers with many players or large builds. Would really appreciate this being a higher priority, as it's preventing WeaponCore deployment on my server.

**Comment by sstixrud** [comment]
It is not a matter of not wanting to fix it or it needing to be a higher priority.  The issue is work was done to make WC compatible with Torch Concealment, following the authors recommendations and this did not lead to success.    We will come back when either 1) We have another idea on how to fix it or 2) There is more information made available for why its failing.

**Comment by SeanTrig** [comment]
Very well, thank you for the response.

**Comment by sstixrud** [comment]
This may be fixed.  Please confirm

**Comment by SeanTrig** [comment]
Server is online. We have one crash from this morning 10 seconds after WeaponCore weapons started firing. https://pastebin.com/2hKbb5Vk

I am unsure whether the crash was due to WeaponCore, the phaser mod I'm using or incompatibility with another mod. Server came back online without a problem. I'll keep a record of any errors or odd behavior and keep you posted.

**Comment by SeanTrig** [comment]
Several days online: no crashes related to WeaponCore and Concealment is working as expected.

**Comment by sstixrud** [comment]
Fixed
