### ISSUE TITLE
Ai computer not owned

### ISSUE THREAD

**Issue by Reno77idk** [sstixrud/WeaponCore#435]
Is this a multiplayer or singleplayer bug?
This is a singleplayer bug

Describe the bug:
When i get into any cockpit or any control station it shows this message:
Ai computer is not owned, take ownership of grid weapons! - current ownerld is: 0
And all of the weapons have like a red box/outline around them
Steps To Reproduce:
Build gun has a red box around it
Enter a cockpit and the message shows
Expected behavior:
When i shot the weapon from a control panel the game crashed

I would provide a screenshot but seems like i can't put a picture here

**Comment by LordKreeg** [comment]
Which weapon mod was used, during this crash \ message?

**Comment by odin0423** [comment]
im having the same issue with any weaponcore weapons on my SE saves after a few hours of play, but i dont get the red box/ outline, and my game doesnt crash

**Comment by Allen-Wrench** [comment]
ive had this happen sometimes when copy/pasting a ship; the pasted copy would have this error with all the weapons. to fix it i just cut the pasted ship, and paste it again, and everything works just fine. i kind of have a feeling its a side effect of some exploit prevention change that was made, possibly.

**Comment by xDaeDaLuSx015** [comment]
I've just run into this issue as well on version 2.2(2) stable as listed on the workshop. Everything was working fine prior to the latest update (the last update fixed the red box issue), i applied the new patch a while ago and now all weaponcore ships have this same AI message. I tried messing about with it and all i was able to determine is that if you remove all weaponcore modules from a ship the error goes away, but if you then add a weaponcore block back it occurs again. However, if you create an entirely new grid and add a weapon core block to it, the error doesn't occur. I was also able to blueprint a non-functional ship and paste it and the error goes away on the copy but persists on the original. Seems like something isn't being set correctly on certain old grids when the update is applied.

**Comment by odin0423** [comment]
Im not having that problem but ive noticed when I switch a grid ownership to nobody so my build and repair system can grind it down I get that same problem, also ive noticed on a certain ship the TID freighter when I build it as if from the sub/download, the scripts it runs crashes weaponcore the same way, the ai issue. Do you do something similar to what I do or do you not use the build and repair system by “dummy industries” I don’t remember the author lol   Sent from Mail for Windows 10 From: xDaeDaLuSx015Sent: Sunday, January 23, 2022 2:49 PMTo: sstixrud/WeaponCoreCc: odin0423; CommentSubject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) I've just run into this issue as well on version 2.2(2) stable as listed on the workshop. Everything was working fine prior to the latest update (the last update fixed the red box issue), i applied the new patch a while ago and now all weaponcore ships have this same AI message. I tried messing about with it and all i was able to determine is that if you remove all weaponcore modules from a ship the error goes away, but if you then add a weaponcore block back it occurs again. However, if you create an entirely new grid and add a weapon core block to it, the error doesn't occur. I was also able to blueprint a non-functional ship and paste it and the error goes away on the copy but persists on the original. Seems like something isn't being set correctly on certain old grids when the update is applied.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by odin0423** [comment]
I get that issue when I build/ paste the TID freighter that I subbed/downloaded and when I switch NPC grids from MES to a nobody owned but currently that’s the only thing ive found so far. Its not confirmed as of yet, so don’t take it as a bandaid type fix  Sent from Mail for Windows 10 From: dudeSent: Friday, January 21, 2022 4:54 AMTo: sstixrud/WeaponCoreCc: odin0423; CommentSubject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) ive had this happen sometimes when copy/pasting a ship; the pasted copy would have this error with all the weapons. to fix it i just cut the pasted ship, and paste it again, and everything works just fine. i kind of have a feeling its a side effect of some exploit prevention change that was made, possibly.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by odin0423** [comment]
O also its not a actual fix that ive found yet im still plugging away on my end before I notify the devs/dev. Sent from Mail for Windows 10 From: xDaeDaLuSx015Sent: Sunday, January 23, 2022 2:49 PMTo: sstixrud/WeaponCoreCc: odin0423; CommentSubject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) I've just run into this issue as well on version 2.2(2) stable as listed on the workshop. Everything was working fine prior to the latest update (the last update fixed the red box issue), i applied the new patch a while ago and now all weaponcore ships have this same AI message. I tried messing about with it and all i was able to determine is that if you remove all weaponcore modules from a ship the error goes away, but if you then add a weaponcore block back it occurs again. However, if you create an entirely new grid and add a weapon core block to it, the error doesn't occur. I was also able to blueprint a non-functional ship and paste it and the error goes away on the copy but persists on the original. Seems like something isn't being set correctly on certain old grids when the update is applied.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by xDaeDaLuSx015** [comment]
We don't run any repair mod on our server, no.

**Comment by odin0423** [comment]
Okay do you switch grid ownership like I do? Sent from Mail for Windows 10 From: xDaeDaLuSx015Sent: Sunday, January 23, 2022 2:59 PMTo: sstixrud/WeaponCoreCc: odin0423; CommentSubject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) We don't run any repair mod on our server, no.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by xDaeDaLuSx015** [comment]
No, all the ships we have affected since the update were build from scratch, some by welder array from single player blueprint and others completely from scratch.

**Comment by odin0423** [comment]
If you guys aren’t running scripts then idk and the crappy thing is I cant replicate your problem on my own to help you find a work around like mine  Sent from Mail for Windows 10 From: xDaeDaLuSx015Sent: Sunday, January 23, 2022 3:06 PMTo: sstixrud/WeaponCoreCc: odin0423; CommentSubject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) No, all the ships we have affected since the update were build from scratch, some by welder array from single player blueprint and others completely from scratch.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by xDaeDaLuSx015** [comment]
Just to update this, on our server this resolved itself. I don't think the server was actually played on so i'm not sure what caused the change. I guess it either means this was a client side bug or something on the server was being slow to update after the initial upgrade of the mods via workshop.

**Comment by sstixrud** [comment]
Provide the coresystems debug.log for the client and server for the play sessions where the crashed occurred and I will take a look.

**Comment by odin0423** [comment]
I'm still unsure on how to get that to function and so far with my temp fix I can still play, as long as I dont switch ownership of ships that a npc through MES modsSent via the Samsung Galaxy S8 Active, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Shane Stixrud ***@***.***> Date: 25/1/22  20:46  (GMT-05:00) To: sstixrud/WeaponCore ***@***.***> Cc: odin0423 ***@***.***>, Comment ***@***.***> Subject: Re: [sstixrud/WeaponCore] Ai computer not owned (Issue #435) 
Provide the coresystems debug.log for the client and server for the play sessions where the crashed occurred and I will take a look.
