### ISSUE TITLE
No Grid Damage & No Turret Targetting

### ISSUE THREAD

**Issue by Emberkade** [sstixrud/WeaponCore#66]
Currently running into two issues. First and foremost is that no matter what weapon I use or the range, none of the Weapon Core turrets and fixed weapons cause any grid damage. I have looked through my server files to make sure grid damage is enabled, so I'm not entirely sure what the cause is.
Additionally, all turrets simply fire in a forward-facing position, they do not turn to target enemies at all. All turrets will fire with the left mouse, but they will only fire in whatever position they were placed.

All of this is on a dedicated server running North Wind Weapons, Weapon Core Vanilla Replacement, the MexPex MWI Weaponcore conversion, and the MWI homing weapons. I am also using Whiplashes new rail gun mod, as well as Directed Energy Weapons, not sure if that matters.

**Comment by Xeno1177** [comment]
Turrets appear to do no damage to enemy grids.  Hit decals are displayed and bullet impact sounds are played but no physical damage occurs.  Tested with Vanilla, Octobeam, and MA Weapons.  When loading non-weaponcore weapons alongside weaponcore weapons, the non-weaponcore weapons do damage as expected.  

[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4351067/debugdevelop.log)

**Comment by Mashednz** [comment]
Same problem running a Torch server. After reading through some comments on workshop it points me to believe that Concealment plugin could be responsible for this. unfortunately thats a deal breaker for my server as running without concealment results in horrible sim. hope this can be fixed.

**Comment by sstixrud** [comment]
This is something the concealment plugin will need to fix.   The concealment plugin causes issues with multiple mods, including two of mine, I am not going to spending anymore time working around plugins that break mods that are working as designed.

**Comment by rexxar-tc** [comment]
Concealment provides several methods for mods to detect and prevent concealment of grids. We *cannot* cater to every mod. Not we won't, or we don't want to, we ***can't***. 

There is one concealment plugin, which provides a standard way for every mod to interact with it. There are an infinite number of mods, every single one works a different way, and absolutely none of them provide any way for us to interact with them. 

It is simply not possible for us to cater to every single mod author that is too lazy or stubborn to work within a framework that the *vast* majority of servers use.

Honestly, what do you expect me to do? Reverse engineer your particular mod and inject code to work with concealment? Somehow replicate your network communications? There simply is not any options available to me to make your mod work with concealment. 

You don't get to blame me for problems I have no way of solving when you have some very easy options available to you.

**Comment by Mashednz** [comment]
Given how many people use concealment on their platform because they dont have super computers available to run regular SEDS it would be silly to restrict your mod to just those servers, and like most I will choose 1.0 sim over your mod and 0.4 sim every time.

It's a shame as I had looked forward to this mod making MP and I know my players had to but I guess we will manage with regular weapons.

**Comment by sstixrud** [comment]
@rexxar-tc It is not at all clear what WeaponCore would need to do to be compatible with concealment.  Short of disabling concealment for every grid that has a weapon on it (pretty much all grids, at which point, what is the point?).  If you can can provide me with a reasonable solution I will implement it.

**Comment by rexxar-tc** [comment]
It's your code, you tell me. All I can tell you is the plugin gives you a way to check if a grid is concealed. Beyond that, it's up to you. Either suspend the logic, or otherwise deal with the fact that the grid is no longer updating. The only information anyone has ever given me about this is "it's broken".

**Comment by sstixrud** [comment]
@rexxar-tc there is no point in having concealed grids if every grid with a weapon or shield on a server is disabled for concealment.   If you are telling me I would need to add logic to every single method that access MyCubeGrid in order to "Detect" concealment and then take some other action to suspend that check and everything that depends on it then this is beyond absurd.  Weaponcore is nearing 30,000 lines and there are literally hundreds of conditions that would be affected by this.

**Comment by Mashednz** [comment]
Why does it need to be disabled completely when the entire idea of concealment is for it to sake up those grids when players reach a pre determined range from them?

**Comment by sstixrud** [comment]
@Mashednz so it doesn't break weaponcore when it switches to conceal.

**Comment by Mashednz** [comment]
So your saying even if you added whatever you needed to add that any grid with weapon core would have to remain revealed in order to not break all of them?

**Comment by sstixrud** [comment]
@Mashednz yes, same with shields.

**Comment by Mashednz** [comment]
I have shields on mine...not sure if same mod as your thinking of but works fine with concealment...if theres any negative it might be that the charge returns to 0
